"use client"

import { useState } from "react"
import { 
  User, 
  Newspaper, 
  Shield as ShieldIcon, 
  Building2, 
  Download, 
  Send, 
  FileText, 
  Copy, 
  Clock,
  CheckCircle,
  AlertTriangle,
  ArrowLeft,
  ExternalLink,
  Hash
} from "lucide-react"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card"
import { useToast } from "@/hooks/use-toast"
import type { Role } from "@/components/login-page"

interface RoleBasedOutputProps {
  userRole: Role
  onAction: () => void
  onBack: () => void
}

// Dummy data
const analysisData = {
  caseId: "BS-10234",
  hash: "a7f8c3d2e9b1f5a6c8d4e2b7f9a3c5d8e1b4f6a9c2d5e8b1f3a6c9d2e5b8f1a4",
  timestamp: "2024-01-15 14:32:45 IST",
  verdict: "Likely Deepfake",
  confidence: 87,
  categories: [
    { name: "Face Analysis", score: 92, status: "suspicious" },
    { name: "Audio Sync", score: 78, status: "suspicious" },
    { name: "Metadata", score: 65, status: "warning" },
    { name: "Source Verification", score: 45, status: "uncertain" },
  ],
  custodyLog: [
    { time: "14:30:12", event: "Media received", actor: "System" },
    { time: "14:30:15", event: "SHA-256 hash generated", actor: "System" },
    { time: "14:30:18", event: "Evidence locked", actor: "System" },
    { time: "14:32:45", event: "Analysis complete", actor: "AI Engine" },
    { time: "14:35:22", event: "Report generated", actor: "System" },
  ],
}

// Mock file download function
const downloadMockFile = (filename: string, content: string) => {
  const blob = new Blob([content], { type: "text/plain" })
  const url = URL.createObjectURL(blob)
  const a = document.createElement("a")
  a.href = url
  a.download = filename
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}

// Generate mock report content
const generateReportContent = () => {
  return `
╔════════════════════════════════════════════════════════════════════╗
║                    BHARATSHIELD ANALYSIS REPORT                    ║
╚════════════════════════════════════════════════════════════════════╝

CASE ID: ${analysisData.caseId}
GENERATED: ${new Date().toLocaleString()}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

VERDICT: ${analysisData.verdict}
CONFIDENCE: ${analysisData.confidence}%

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

EVIDENCE HASH (SHA-256):
${analysisData.hash}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

ANALYSIS BREAKDOWN:
${analysisData.categories.map(c => `  • ${c.name}: ${c.score}% (${c.status})`).join('\n')}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

CHAIN OF CUSTODY:
${analysisData.custodyLog.map(log => `  [${log.time}] ${log.event} - ${log.actor}`).join('\n')}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

SUMMARY:
Multi-modal analysis indicates high probability of synthetic manipulation.
Primary concerns include facial inconsistencies and audio synchronization
issues. Metadata analysis shows evidence of post-processing across
multiple editing sessions.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

This report is generated by BharatShield Deepfake Detection Platform.
For verification, use the SHA-256 hash provided above.

© 2024 BharatShield. All rights reserved.
`.trim()
}

// Generate mock takedown notice
const generateTakedownNotice = () => {
  return `
╔════════════════════════════════════════════════════════════════════╗
║                      OFFICIAL TAKEDOWN NOTICE                       ║
╚════════════════════════════════════════════════════════════════════╝

NOTICE ID: TDN-${analysisData.caseId}
DATE ISSUED: ${new Date().toLocaleString()}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

TO: Platform Administrator
RE: Removal of Synthetic/Manipulated Media Content

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

CONTENT IDENTIFICATION:
Case Reference: ${analysisData.caseId}
Evidence Hash: ${analysisData.hash}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

FINDINGS:
The above-referenced content has been analyzed using advanced deepfake
detection technology and has been determined to be synthetically
manipulated with ${analysisData.confidence}% confidence.

ACTION REQUIRED:
Pursuant to applicable laws and platform policies regarding synthetic
media and misinformation, you are hereby requested to:

1. Remove the identified content from your platform immediately
2. Preserve all metadata and logs related to the content
3. Provide information about the content uploader if legally required
4. Confirm compliance within 48 hours

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

AUTHORITY:
This notice is issued under the authority of the designated
regulatory body for digital content compliance.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Generated by BharatShield Deepfake Detection Platform
`.trim()
}

export function RoleBasedOutput({ userRole, onAction, onBack }: RoleBasedOutputProps) {
  const [copied, setCopied] = useState(false)
  const { toast } = useToast()

  const copyHash = () => {
    navigator.clipboard.writeText(analysisData.hash)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  const getStatusColor = (status: string) => {
    switch (status) {
      case "suspicious": return "text-verdict-fake"
      case "warning": return "text-verdict-uncertain"
      case "uncertain": return "text-muted-foreground"
      default: return "text-verdict-real"
    }
  }

  // Action handlers with toast notifications
  const handleDownloadReport = () => {
    downloadMockFile(`BharatShield_Report_${analysisData.caseId}.txt`, generateReportContent())
    toast({
      title: "Report downloaded successfully",
      description: `File: BharatShield_Report_${analysisData.caseId}.txt`,
    })
  }

  const handleExportPDF = () => {
    downloadMockFile(`BharatShield_Evidence_${analysisData.caseId}.txt`, generateReportContent())
    toast({
      title: "PDF exported successfully",
      description: `Evidence package for Case ${analysisData.caseId}`,
    })
  }

  const handleGenerateTakedown = () => {
    downloadMockFile(`Takedown_Notice_${analysisData.caseId}.txt`, generateTakedownNotice())
    toast({
      title: "Takedown notice generated",
      description: "Official notice ready for distribution",
    })
  }

  const handleForwardToPlatform = () => {
    toast({
      title: "Notice forwarded to platform successfully",
      description: `Case ${analysisData.caseId} sent for review`,
    })
  }

  const handleReportToAuthorities = () => {
    onAction()
  }

  return (
    <div className="min-h-screen flex flex-col">
      {/* Header */}
      <header className="border-b border-border px-6 py-4">
        <div className="max-w-5xl mx-auto flex items-center gap-4">
          <Button variant="ghost" size="sm" onClick={onBack}>
            <ArrowLeft className="w-4 h-4 mr-2" />
            Back
          </Button>
          <div className="flex items-center gap-3">
            <div className="p-2 bg-primary/10 rounded-lg">
              <ShieldIcon className="w-5 h-5 text-primary" />
            </div>
            <span className="font-semibold">BharatShield</span>
          </div>
          <span className="text-muted-foreground">/</span>
          <span className="text-muted-foreground">Take Action</span>
        </div>
      </header>

      <main className="flex-1 px-6 py-8">
        <div className="max-w-5xl mx-auto space-y-8">
          {/* Role Content */}
          <Card className="bg-card border-border">
            <CardContent className="pt-6">
                {/* Citizen View */}
                {userRole === "Citizen" && (
                  <div className="space-y-6">
                  <Card className="bg-verdict-fake/5 border-verdict-fake/30">
                    <CardContent className="p-6">
                      <div className="flex items-start gap-4">
                        <div className="p-3 bg-verdict-fake/10 rounded-xl">
                          <AlertTriangle className="w-8 h-8 text-verdict-fake" />
                        </div>
                        <div className="flex-1">
                          <h3 className="text-xl font-semibold text-verdict-fake">
                            {analysisData.verdict}
                          </h3>
                          <p className="text-muted-foreground mt-1">
                            This media has been identified as potentially manipulated. 
                            We recommend reporting this to the appropriate authorities.
                          </p>
                        </div>
                        <div className="text-right">
                          <div className="text-2xl font-bold text-verdict-fake">
                            {analysisData.confidence}%
                          </div>
                          <div className="text-sm text-muted-foreground">
                            confidence
                          </div>
                        </div>
                      </div>
                    </CardContent>
                  </Card>

                  <div className="flex flex-col sm:flex-row gap-4">
                    <Button 
                      size="lg" 
                      onClick={handleReportToAuthorities}
                      className="flex-1 bg-primary hover:bg-primary/90 gap-2"
                    >
                      <Send className="w-5 h-5" />
                      Report to Authorities
                    </Button>
                    <Button 
                      size="lg" 
                      variant="outline"
                      className="flex-1 gap-2"
                    >
                      <ExternalLink className="w-5 h-5" />
                      Learn More
                    </Button>
                  </div>
                  </div>
                )}

                {/* Journalist View */}
                {userRole === "Journalist" && (
                  <div className="space-y-6">
                  <div className="grid md:grid-cols-2 gap-6">
                    <Card className="bg-card border-border">
                      <CardHeader className="pb-2">
                        <CardTitle className="text-lg">Analysis Breakdown</CardTitle>
                      </CardHeader>
                      <CardContent className="space-y-4">
                        {analysisData.categories.map((category) => (
                          <div key={category.name} className="space-y-2">
                            <div className="flex justify-between text-sm">
                              <span>{category.name}</span>
                              <span className={getStatusColor(category.status)}>
                                {category.score}%
                              </span>
                            </div>
                            <div className="h-2 bg-secondary rounded-full overflow-hidden">
                              <div 
                                className={`h-full rounded-full transition-all ${
                                  category.status === "suspicious" 
                                    ? "bg-verdict-fake" 
                                    : category.status === "warning"
                                      ? "bg-verdict-uncertain"
                                      : "bg-muted-foreground"
                                }`}
                                style={{ width: `${category.score}%` }}
                              />
                            </div>
                          </div>
                        ))}
                      </CardContent>
                    </Card>

                    <Card className="bg-card border-border">
                      <CardHeader className="pb-2">
                        <CardTitle className="text-lg">Summary</CardTitle>
                      </CardHeader>
                      <CardContent className="space-y-4">
                        <div className="p-4 bg-secondary rounded-lg">
                          <p className="text-sm leading-relaxed">
                            Multi-modal analysis indicates high probability of synthetic manipulation. 
                            Primary concerns include facial inconsistencies and audio synchronization issues. 
                            Metadata analysis shows evidence of post-processing across multiple editing sessions.
                          </p>
                        </div>
                        <div className="flex items-center gap-2 text-sm text-muted-foreground">
                          <Clock className="w-4 h-4" />
                          <span>Analyzed: {analysisData.timestamp}</span>
                        </div>
                      </CardContent>
                    </Card>
                  </div>

                  <Button 
                    size="lg" 
                    onClick={handleDownloadReport}
                    className="w-full bg-primary hover:bg-primary/90 gap-2"
                  >
                    <Download className="w-5 h-5" />
                    Download Detailed Report
                  </Button>
                  </div>
                )}

                {/* Police View */}
                {userRole === "Police" && (
                  <div className="space-y-6">
                  <div className="grid md:grid-cols-2 gap-6">
                    <Card className="bg-card border-border">
                      <CardHeader className="pb-2">
                        <CardTitle className="text-lg flex items-center gap-2">
                          <Hash className="w-5 h-5" />
                          Evidence Hash
                        </CardTitle>
                      </CardHeader>
                      <CardContent className="space-y-4">
                        <div className="p-4 bg-secondary rounded-lg">
                          <div className="flex items-start justify-between gap-4">
                            <code className="text-xs font-mono break-all text-muted-foreground">
                              {analysisData.hash}
                            </code>
                            <Button
                              variant="ghost"
                              size="icon"
                              onClick={copyHash}
                              className="shrink-0"
                            >
                              {copied ? (
                                <CheckCircle className="w-4 h-4 text-verdict-real" />
                              ) : (
                                <Copy className="w-4 h-4" />
                              )}
                            </Button>
                          </div>
                        </div>
                        <div className="text-xs text-muted-foreground">
                          SHA-256 cryptographic hash for evidence verification
                        </div>
                      </CardContent>
                    </Card>

                    <Card className="bg-card border-border">
                      <CardHeader className="pb-2">
                        <CardTitle className="text-lg flex items-center gap-2">
                          <Clock className="w-5 h-5" />
                          Chain of Custody
                        </CardTitle>
                      </CardHeader>
                      <CardContent>
                        <div className="space-y-3">
                          {analysisData.custodyLog.map((log, index) => (
                            <div 
                              key={index}
                              className="flex items-start gap-3 text-sm"
                            >
                              <div className="w-2 h-2 rounded-full bg-primary mt-2 shrink-0" />
                              <div className="flex-1">
                                <div className="flex justify-between">
                                  <span className="font-medium">{log.event}</span>
                                  <span className="text-muted-foreground font-mono text-xs">
                                    {log.time}
                                  </span>
                                </div>
                                <span className="text-xs text-muted-foreground">
                                  by {log.actor}
                                </span>
                              </div>
                            </div>
                          ))}
                        </div>
                      </CardContent>
                    </Card>
                  </div>

                  <Card className="bg-card border-border">
                    <CardContent className="p-4">
                      <div className="flex items-center justify-between">
                        <div className="flex items-center gap-4">
                          <div className="p-2 bg-primary/10 rounded-lg">
                            <FileText className="w-5 h-5 text-primary" />
                          </div>
                          <div>
                            <div className="font-medium">Case ID: {analysisData.caseId}</div>
                            <div className="text-sm text-muted-foreground">
                              Ready for official documentation
                            </div>
                          </div>
                        </div>
                        <Button onClick={handleExportPDF} className="gap-2">
                          <Download className="w-4 h-4" />
                          Export PDF
                        </Button>
                      </div>
                    </CardContent>
                  </Card>
                  </div>
                )}

                {/* Authority View */}
                {userRole === "Authority" && (
                  <div className="space-y-6">
                  <Card className="bg-card border-border">
                    <CardHeader>
                      <CardTitle className="flex items-center gap-2">
                        <Building2 className="w-5 h-5" />
                        Administrative Actions
                      </CardTitle>
                      <CardDescription>
                        Case ID: {analysisData.caseId}
                      </CardDescription>
                    </CardHeader>
                    <CardContent className="space-y-4">
                      <div className="grid sm:grid-cols-2 gap-4">
                        <Button 
                          size="lg" 
                          onClick={handleGenerateTakedown}
                          className="h-auto py-6 flex-col gap-2 bg-verdict-fake hover:bg-verdict-fake/90"
                        >
                          <AlertTriangle className="w-6 h-6" />
                          <span>Generate Takedown Notice</span>
                        </Button>
                        <Button 
                          size="lg" 
                          variant="outline"
                          onClick={handleForwardToPlatform}
                          className="h-auto py-6 flex-col gap-2"
                        >
                          <Send className="w-6 h-6" />
                          <span>Forward to Platform</span>
                        </Button>
                      </div>
                    </CardContent>
                  </Card>

                  <Card className="bg-card border-border">
                    <CardHeader className="pb-2">
                      <CardTitle className="text-lg">Case Summary</CardTitle>
                    </CardHeader>
                    <CardContent>
                      <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
                        <div className="p-4 bg-secondary rounded-lg text-center">
                          <div className="text-2xl font-bold text-verdict-fake">
                            {analysisData.confidence}%
                          </div>
                          <div className="text-xs text-muted-foreground mt-1">
                            Confidence
                          </div>
                        </div>
                        <div className="p-4 bg-secondary rounded-lg text-center">
                          <div className="text-2xl font-bold text-primary">
                            4
                          </div>
                          <div className="text-xs text-muted-foreground mt-1">
                            Flags Detected
                          </div>
                        </div>
                        <div className="p-4 bg-secondary rounded-lg text-center">
                          <div className="text-2xl font-bold text-foreground">
                            High
                          </div>
                          <div className="text-xs text-muted-foreground mt-1">
                            Priority
                          </div>
                        </div>
                        <div className="p-4 bg-secondary rounded-lg text-center">
                          <div className="text-2xl font-bold text-verdict-real">
                            Ready
                          </div>
                          <div className="text-xs text-muted-foreground mt-1">
                            Status
                          </div>
                        </div>
                      </div>
                    </CardContent>
                  </Card>
                  </div>
                )}
            </CardContent>
          </Card>
        </div>
      </main>
    </div>
  )
}
