# legal.py

from datetime import datetime


def generate_legal_notice(metadata):
    """
    Generates a takedown notice if the content is detected as Fake.

    Parameters:
    - metadata: dictionary containing file details

    Returns:
    - legal notice string (if Fake)
    - None (if Real)
    """

    # Check if detected content is Fake
    if metadata["result"] == "Fake":

        # Create formatted legal notice
        notice = f"""
================= TAKEDOWN NOTICE =================

Subject: Detection of Potential Deepfake Content

This is to inform that the media file '{metadata["file_name"]}' 
has been identified as potentially manipulated (Deepfake).

Details:
- File Name     : {metadata["file_name"]}
- Hash (SHA-256): {metadata["hash"]}
- Timestamp     : {metadata["timestamp"]}
- Detection     : {metadata["result"]}
- Confidence    : {metadata["confidence"]}

Legal Context:
This content may violate IT Rules 2021 related to synthetic media 
and misinformation affecting public trust and security.

Recommended Action:
Immediate review and takedown by the concerned authority/platform.

Generated By:
BharatShield System

Generated On:
{datetime.now().strftime("%Y-%m-%d %H:%M:%S")}

==================================================
"""
        return notice

    # If content is Real → no notice needed
    return None